System.AggregateException: Se han producido uno o varios errores. ---> RtmpSharp.Messaging.InvocationException: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException : An Authentication object was not found in the SecurityContext
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en RtmpSharp.Net.RtmpClient.<InvokeAsync>d__49`1.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en LoLAccountChecker.Checker.<Check>b__21_0(Task`1 url)
   en System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en LoLAccountChecker.Checker.<Check>d__21.MoveNext()
---> (Nº de excepción interna 0) RtmpSharp.Messaging.InvocationException: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException : An Authentication object was not found in the SecurityContext
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en RtmpSharp.Net.RtmpClient.<InvokeAsync>d__49`1.MoveNext()<---

